import Head from "next/head";
import { getDocs, onSnapshot, query, orderBy } from "firebase/firestore";

import Header from "@/components/header/Header";
import Sidebar from "@/components/sidebar/Sidebar";
import Feed from "@/components/feed/Feed";
import Widgets from "@/components/widget/Widgets";
import { Post } from "@/types/feed";
import { postCollection, firestore } from "@/firebase";

export async function getServerSideProps(context: any) {
  let posts: any = [];

  const querySnapshot = await getDocs(postCollection);
  querySnapshot.forEach((doc) => {
    // doc.data() is never undefined for query doc snapshots
    let data = doc.data();
    posts.push({ message: data.message });
  });

  return {
    props: {
      posts,
    },
  };
}

export default function Home() {
  return (
    <div className="h-screen overflow-hidden">
      <Head>
        <title>Facebok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex">
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </div>
  );
}
