import Head from "next/head";
import { useSession } from "next-auth/react";

import Header from "@/components/header/Header";

export default function Home() {
  const userSession = useSession();
  console.log("USER SESSION", userSession);
  return (
    <>
      <Head>
        <title>Facebok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        {/* Sidebar */}
        {/* Feed */}
        {/* Widgets */}
      </main>
    </>
  );
}
