import Head from "next/head";
import { getDocs, query, orderBy, DocumentData } from "firebase/firestore";

import Header from "@/components/header/Header";
import Sidebar from "@/components/sidebar/Sidebar";
import Feed from "@/components/feed/Feed";
import Widgets from "@/components/widget/Widgets";
import { postCollection } from "@/firebase";

export async function getServerSideProps(context: any) {
  let posts: DocumentData = [];

  const q = query(postCollection, orderBy("timestamp", "desc"));
  const querySnapshot = await getDocs(q);
  querySnapshot.forEach((doc) => {
    // doc.data() is never undefined for query doc snapshots
    let data = doc.data();
    posts.push({
      message: data.message,
      image: data.image,
      id: data.id,
      postImage: data.postImage || null,
      name: data.name,
      email: data.email,
      timestamp: { seconds: data.timestamp.seconds },
    });
  });

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }: any) {
  return (
    <div className="h-screen overflow-hidden">
      <Head>
        <title>Facebok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex">
        <Sidebar />
        <Feed posts={posts} />
        <Widgets />
      </main>
    </div>
  );
}
